language: node_js

# clones repository with the quiet flag
git:
  quiet: true

# safelist
branches:
  only:
  - master
  - develop

install:
- nvm use && nvm alias default $(cat .nvmrc)
- npm install -g react-native-cli
- npm install -g detox-cli
- npm install

jobs:
  include:
    - name: Unit tests
      script: npm run test:unit
    - name: Integration iOS tests
      os: osx
      osx_image: xcode11.3
      language: objective-c
      cache:
        cocoapods: true
      before_install:
        - brew tap wix/brew
        - brew install applesimutils
      script:
        - cd ios && pod install && cd ..
        - npm run build:integration:ios:release > ./detox-build.log # output to log file to fix log limit
        - npm run test:integration:ios:release