language: node_js
node_js: lts/*
git:
  quiet: true
env:
  global:
  - ANDROID_API=28
branches:
  only:
  - master
  - develop
cache:
  directories:
  - "$HOME/.npm"
install:
- npm install -g react-native-cli
- npm install -g detox-cli
- npm install
jobs:
  include:
  - name: Unit tests
    script: npm run test:unit
  - name: Integration iOS tests
    os: osx
    osx_image: xcode11.3
    language: objective-c
    cache:
      cocoapods: true
    podfile: "./ios/Podfile"
    before_install:
    - brew tap wix/brew
    - brew install applesimutils
    script:
    - npm run ios:pod:install
    - npm run detox:ios:release:build > /dev/null
    - npm run detox:ios:release:test
  - name: Integration Android tests
    language: android
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
      - "$HOME/.android/build-cache"
    jdk: oraclejdk8
    dist: trusty
    sudo: required
    android:
      components:
      - tools
      - tools
      - platform-tools
      - build-tools-28.0.16
      - android-${ANDROID_API}
      - sys-img-x86-android-28
      licenses:
      - android-sdk-license-.+
    before_install:
    - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in android/RNDetoxTravisTest.keystore.enc -out android/RNDetoxTravisTest.keystore -d
    - yes | sdkmanager "platforms;android-28"
    before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
    install:
    - echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-28;google_apis;x86"
    - echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name pixel_xl
      --device "pixel_xl" -k 'system-images;android-28;google_apis;x86'
    - "$ANDROID_HOME/emulator/emulator -list-avds"
    script:
    - npm install
    - npm run detox:android:release:build
    - npx detox test --headless -c android.emu.release --gpu swiftshader --cleanup
