env:
  global:
  - NODE_VERSION=stable

# clones repository with the quiet flag
git:
  quiet: true

# safelist
branches:
  only:
  - master
  - develop

cache:
  directories:
    - $HOME/.npm

install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- nvm alias default $NODE_VERSION

- npm install -g react-native-cli
- npm install -g detox-cli
- npm ci

jobs:
  include:
    - name: Unit tests
      script: npm run test:unit
    - name: Integration iOS tests
      os: osx
      osx_image: xcode11.3
      language: objective-c
      cache:
        cocoapods: true
        directories:
          - $HOME/.npm
      podfile: ios/Podfile
      before_install:
        - brew tap wix/brew
        - brew install applesimutils
      script:
        - cd ios && pod install && cd ..
        - npm run build:integration:ios:release > ./detox-build.log # output to log file to fix log limit
        - npm run test:integration:ios:release