language: node_js
node_js: 'lts/*'

# clones repository with the quiet flag
git:
  quiet: true

# safelist
branches:
  only:
  - master
  - develop

cache:
  directories:
    - $HOME/.npm

install:
- npm install -g react-native-cli
- npm install -g detox-cli
- npm install

jobs:
  include:
    - name: Unit tests
      script: npm run test:unit
    - name: Integration iOS tests
      os: osx
      osx_image: xcode11.3
      language: objective-c
      cache:
        cocoapods: true
      podfile: ./ios/Podfile
      before_install:
        - brew tap wix/brew
        - brew install applesimutils
      script:
        - npm run ios:pod:install
        - npm run detox:ios:release:build > /dev/null
        - npm run detox:ios:release:test
    - name: Integration Android tests
      language: android
      cache: npm
      jdk: oraclejdk8
      dist: trusty
      sudo: required
      android:
        components:
          - build-tools-28.0.16
          - android-28
          - sys-img-x86-android-28
      
      install:
      - echo no | android create avd --force -n pixel9 -t android-28 --abi default/x86
      - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      - sudo apt-get install -y nodejs

      script:
      - cd src/PowerShare/
      - npm install
      - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - npx detox build -c android.emu.release
      - npx detox test --headless -c android.emu.release --gpu swiftshader --cleanup
