language: node_js
node_js: 'lts/*'

# clones repository with the quiet flag
git:
  quiet: true

# safelist
branches:
  only:
  - master
  - develop

cache:
  directories:
    - $HOME/.npm

install:
- npm install -g react-native-cli
- npm install -g detox-cli
- npm install

jobs:
  include:
    - name: Unit tests
      script: npm run test:unit
    - name: Integration iOS tests
      os: osx
      osx_image: xcode11.3
      language: objective-c
      cache:
        cocoapods: true
      podfile: ./ios/Podfile
      before_install:
        - brew tap wix/brew
        - brew install applesimutils
      script:
        - npm run ios:pod:install
        - npm run detox:ios:release:build > /dev/null
        - npm run detox:ios:release:test