language: node_js
node_js: lts/*
git:
  quiet: true
env:
  global:
  - ANDROID_API=28
branches:
  only:
  - master
  - develop
cache:
  directories:
  - "$HOME/.npm"
install:
- npm install -g react-native-cli
- npm install -g detox-cli
- npm install
jobs:
  include:
  - name: Unit tests
    script: npm run test:unit
  - name: Integration iOS tests
    os: osx
    osx_image: xcode11.3
    language: objective-c
    cache:
      cocoapods: true
    podfile: "./ios/Podfile"
    before_install:
    - brew tap wix/brew
    - brew install applesimutils
    script:
    - npm run ios:pod:install
    - npm run detox:ios:release:build > /dev/null
    - npm run detox:ios:release:test
  - name: Integration Android tests
    language: android
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache
    jdk: oraclejdk8
    dist: trusty
    sudo: required
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.16
        - android-${ANDROID_API}
        - sys-img-x86-android-28
        - extra
      licenses:
        - android-sdk-license-.+
    before_install:
      - openssl aes-256-cbc -K $encrypted_b6e934f6223e_key -iv $encrypted_b6e934f6223e_iv -in android/RNDetoxTravisTest.keystore.enc -out android/RNDetoxTravisTest.keystore -d
      # Install the rest of tools (e.g. avdmanager)
      # - sdkmanager tools
      # Create and start emulator for the script. Meant to race the install task.
      - echo no | android create avd --force --name pixel_xl --device "pixel_xl" -n test -t android-28 --abi x86 -c 100M
    install:
      - npm install
    script:
      - npm run detox:android:release:build
      - npx detox test --headless -c android.emu.release --gpu swiftshader --cleanup
